# Generated by Django 6.0.1 on 2026-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('summer_value', models.IntegerField(help_text='Summer register reading')),
                ('winter_value', models.IntegerField(help_text='Winter register reading')),
                ('summer_usage', models.IntegerField(editable=False, help_text='Calculated summer usage delta')),
                ('winter_usage', models.IntegerField(editable=False, help_text='Calculated winter usage delta')),
                ('locked_winter_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('locked_summer_price_low', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('locked_summer_price_high', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('locked_summer_threshold', models.IntegerField(editable=False)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='TariffConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_price', models.DecimalField(decimal_places=2, help_text='Price per kWh for winter season', max_digits=10)),
                ('summer_price_low', models.DecimalField(decimal_places=2, help_text='Discounted price below quota', max_digits=10)),
                ('summer_price_high', models.DecimalField(decimal_places=2, help_text='Market price above quota', max_digits=10)),
                ('summer_threshold', models.IntegerField(help_text='Yearly summer quota threshold in kWh')),
            ],
            options={
                'verbose_name': 'Tariff Configuration',
                'verbose_name_plural': 'Tariff Configuration',
            },
        ),
    ]
