# Generated by Django 6.0.1 on 2026-05-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['reading_date'], name='reading_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('reading_date',), name='unique_reading_date'),
        ),
    ]
